services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notiz-anwendung
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=${DATABASE_COMPOSE_URL}
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_TRUST_HOST=TRUE
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_DISCORD_ID=${AUTH_DISCORD_ID}
      - AUTH_DISCORD_SECRET=${AUTH_DISCORD_SECRET}

    depends_on:
      - db
      - mailhog

  dbPusher:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_COMPOSE_URL}
    depends_on:
      - db
    command: >
      sh -c "npm install && npx prisma db push"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # MailHog Web UI
      - "1025:1025" # SMTP Server

volumes:
  db_data:
