services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notiz-anwendung
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=${DATABASE_COMPOSE_URL}
      - NEXTAUTH_URL=http://notes.localhost
      - AUTH_TRUST_HOST=TRUE
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_DISCORD_ID=${AUTH_DISCORD_ID}
      - AUTH_DISCORD_SECRET=${AUTH_DISCORD_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`notes.localhost`)"
      - "traefik.http.middlewares.app.ratelimit.average=50"
      - "traefik.http.middlewares.app.rateLimit.burst=100"
      - "traefik.http.routers.app.middlewares=app@docker"
    depends_on:
      - db
      - mailhog

  dbPusher:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_COMPOSE_URL}
    depends_on:
      - db
    command: >
      sh -c "npm install && npx prisma db push"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # MailHog Web UI
      - "1025:1025" # SMTP Server

volumes:
  db_data:
