name: Docker Build and Test

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with: 
            node-version: lts/*

    - name: Install Docker using Docker's official script
      run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Install dependencies
      run: npm ci

    - name: Start application-specific services using Docker Compose
      run: docker compose up --build -d
      working-directory: .

    - name: Install Playwright Browser
      run: npx playwright install --with-deps

    - name: Run Playwright Frontend tests
      run: npx playwright test tests/frontendTest.spec.ts 
    - name: Run Playwright Backend tests
      run: npx playwright test test/backendTest.spec.ts

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    
      

      
 
    

   
